<?php
/**
 * @package WP Helpdesk
 */

return array(
	'sla_first_response_hours' => 24,
	'sla_resolution_hours'     => 72,
	'pagination_per_page'      => 20,
	'guest_session_ttl'        => DAY_IN_SECONDS,
	'ticket_start_number'      => 1000,
	'ticket_counter'           => 1000,
	'general_ticket_number_start' => 1000,
	'general_ticket_number_increment' => 1,
	'general_default_status'   => 'open',
	'general_default_priority' => 'normal',
	'general_allow_guest_tickets' => 1,
	'general_require_topic'    => 1,
	'general_auto_assign_mode' => 'none',
	'general_timezone_mode'    => 'network',
	'general_date_format'      => 'wp_default',
	'email_header_html'        => '',
	'email_footer_html'        => '',
	'email_from_name'          => '',
	'email_from_address'       => '',
	'email_reply_to_address'   => '',
	'email_footer_enabled'     => 1,
	'email_header_enabled'     => 1,
	'push_enabled'             => 0,
	'fcm_server_key'           => '',
	'fcm_project_id'           => '',
	'fcm_service_account_json' => '',
	'fcm_mode'                 => 'legacy',
	'push_ticket_events'       => array(),
	'api_enabled'              => 1,
	'api_require_application_passwords' => 1,
	'api_rate_limit_per_minute' => 60,
	'api_log_requests'         => 0,
	'api_allowed_origins'      => '',
);
